CREATE TABLE resenas (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         producto_id VARCHAR(50) NOT NULL,
                         calificacion INT NOT NULL,
                         comentario VARCHAR(500) NOT NULL,
                         fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);